module.exports.makeAndModels = {
  Abiljo: ["Unspecified"],
  Acm: ["Unspecified"],
  Ag: ["Unspecified"],
  Akc: ["Unspecified"],
  Allied: ["Unspecified"],
  Ammann: ["Unspecified"],
  Arden: ["Unspecified"],
  Atlas: ["Unspecified"],
  Ausa: ["Unspecified"],
  "Aveling barfrd": ["Unspecified"],
  Barford: ["Unspecified"],
  Bell: ["Unspecified"],
  Bobcat: ["Unspecified"],
  Bomag: ["Unspecified"],
  Boss: ["Unspecified"],
  Bph: ["Unspecified"],
  "Brian james": ["Unspecified"],
  "Brown and lennox": ["Unspecified"],
  Bt: ["Unspecified"],
  Buccaneer: ["Unspecified"],
  Carter: ["Unspecified"],
  Case: ["Unspecified"],
  Catapillar: ["Unspecified"],
  Cesab: ["Unspecified"],
  Claas: ["Unspecified"],
  Clark: ["Unspecified"],
  Colmar: ["Unspecified"],
  Conquip: ["Unspecified"],
  Cormidi: ["Unspecified"],
  Daewoo: ["Unspecified"],
  Daf: ["Unspecified"],
  Debon: ["Unspecified"],
  Dehaco: ["Unspecified"],
  Dennison: ["Unspecified"],
  Deutz: ["Unspecified"],
  Dieci: ["Unspecified"],
  Dk: ["Unspecified"],
  Doosan: ["Unspecified"],
  Dynapac: ["Unspecified"],
  Dressta: ["Unspecified"],
  Doppstadt: ["Unspecified"],
  Ep: ["Unspecified"],
  "Es soosan": ["Unspecified"],
  Extec: ["Unspecified"],
  Fassi: ["Unspecified"],
  Fendt: ["Unspecified"],
  "Fg wilson": ["Unspecified"],
  "Fiat-hitachi": ["Unspecified"],
  Furukawa: ["Unspecified"],
  Gehl: ["Unspecified"],
  Geith: ["Unspecified"],
  Genie: ["Unspecified"],
  Genmac: ["Unspecified"],
  Genset: ["Unspecified"],
  Gileskips: ["Unspecified"],
  "Goodwin barsby": ["Unspecified"],
  "Graham edwards": ["Unspecified"],
  Groundhog: ["Unspecified"],
  "Gyru star": ["Unspecified"],
  Hamm: ["Unspecified"],
  Hardlife: ["Unspecified"],
  Haulotte: ["Unspecified"],
  Hinowa: ["Unspecified"],
  Hitachi: ["Unspecified"],
  Hyundai: ["Unspecified"],
  Hyster: ["Unspecified"],
  Hymix: ["Unspecified"],
  "Ifor williams": ["Unspecified"],
  Indeco: ["Unspecified"],
  Indespension: ["Unspecified"],
  Iveco: ["Unspecified"],
  Jcb: ["Unspecified"],
  Jlg: ["Unspecified"],
  "John deere": ["Unspecified"],
  Johnston: ["Unspecified"],
  Jpm: ["Unspecified"],
  Jungheinrich: ["Unspecified"],
  Kaeser: ["Unspecified"],
  Kalmar: ["Unspecified"],
  Kato: ["Unspecified"],
  Kersten: ["Unspecified"],
  Kobelco: ["Unspecified"],
  Kamatsu: ["Unspecified"],
  Kommtek: ["Unspecified"],
  Kramer: ["Unspecified"],
  Krupp: ["Unspecified"],
  Kubota: ["Unspecified"],
  Liebherr: ["Unspecified"],
  Linde: ["Unspecified"],
  Liugong: ["Unspecified"],
  Mac: ["Unspecified"],
  Manitou: ["Unspecified"],
  "Massey furguson": ["Unspecified"],
  Mb: ["Unspecified"],
  Mccloskey: ["Unspecified"],
  Mecalac: ["Unspecified"],
  Merlo: ["Unspecified"],
  Mitsubishi: ["Unspecified"],
  Moffett: ["Unspecified"],
  Montabert: ["Unspecified"],
  Montraco: ["Unspecified"],
  Moxy: ["Unspecified"],
  Mustang: ["Unspecified"],
  Mutley: ["Unspecified"],
  Neuson: ["Unspecified"],
  "New holland": ["Unspecified"],
  Nissan: ["Unspecified"],
  Okada: ["Unspecified"],
  Other: ["Unspecified"],
  Osa: ["Unspecified"],
  Perkins: ["Unspecified"],
  Powerpac: ["Unspecified"],
  Powerscreen: ["Unspecified"],
  Pramac: ["Unspecified"],
  Prodem: ["Unspecified"],
  Putzmeister: ["Unspecified"],
  Rammax: ["Unspecified"],
  Rammer: ["Unspecified"],
  Rhino: ["Unspecified"],
  Sami: ["Unspecified"],
  Sany: ["Unspecified"],
  Scania: ["Unspecified"],
  Schwing: ["Unspecified"],
  Sdc: ["Unspecified"],
  Sennebogen: ["Unspecified"],
  Stelco: ["Unspecified"],
  Stiga: ["Unspecified"],
  Sumitomo: ["Unspecified"],
  Takeuchi: ["Unspecified"],
  Terex: ["Unspecified"],
  Thwaites: ["Unspecified"],
  Toyota: ["Unspecified"],
  Volvo: ["Unspecified"],
  Venieri: ["Unspecified"],
  Viking: ["Unspecified"],
  "Wacker neuson": ["Unspecified"],
  Wiedemann: ["Unspecified"],
  Yale: ["Unspecified"],
  Yanmar: ["Unspecified"],
  Zoomlion: ["Unspecified"],
};

module.exports.countryAndCity = {
  Ghana: [
    "Accra",
    "Kumasi",
    "Tamale",
    "Sekondi-Takoradi",
    "Ashaiman",
    "Sunyani",
    "Cape Coast",
    "Obuasi",
    "Teshie",
    "Tema",
    "Koforidua",
    "Wa",
    "Techiman",
    "Ho",
    "Tema New Town",
    "Oduponkpehe",
    "Ejura",
    "Bawku",
    "Aflao",
    "Agona Swedru",
    "Bolgatanga",
    "Tafo",
    "Berekum",
    "Nkawkaw",
    "Akim Oda",
    "Winneba",
    "Hohoe",
    "Yendi",
    "Suhum",
    "Kintampo",
    "Adenta East",
    "Nsawam",
    "Mampong",
    "Konongo",
    "Asamankese",
    "Wenchi",
    "Savelugu",
    "Agogo",
    "Anloga",
    "Prestea",
    "Effiakuma",
    "Tarkwa",
    "Elmina",
    "Dunkwa-on-Offin",
    "Begoro",
    "Kpandu",
    "Kintampo",
    "Navrongo",
    "Axim",
    "Apam",
    "Salaga",
    "Saltpond",
    "Akwatia",
    "Shama",
    "Keta",
    "Nyakrom",
    "Bibiani",
    "Somanya",
    "Foso",
    "Nyankpala",
    "Aburi",
    "Mumford",
    "Bechem",
    "Duayaw Nkwanta",
    "Kade",
    "Anomabu",
    "Akropong",
    "Kete-Krachi",
    "Kibi",
    "Kpandae",
    "Mpraeso",
    "Akim Swedru",
    "Aboso",
    "Bekwai",
    "Drobo",
    "Banda Ahenkro",
    "Dodowa",
    "Larteh Akuapim",
  ],
  Nigeria: [
    "Lagos",
    "Kano",
    "Ibadan",
    "Benin City",
    "Port Harcourt",
    "Jos",
    "Ilorin",
    "Abuja",
    "Kaduna",
    "Enugu",
    "Zaria",
    "Ogbomosho",
    "Warri",
    "Ikorodu",
    "Aba",
    "Maiduguri",
    "Ife",
    "Bauchi",
    "Akure",
    "Abeokuta",
    "Uyo",
    "Oyo",
    "Sokoto",
    "Owerri",
    "Yola",
    "Calabar",
    "Umuahia",
    "Ondo",
    "Minna",
    "Lafia",
    "Okene",
    "Katsina",
    "Ikeja",
    "Nsukka",
    "Ado Ekiti",
    "Awka",
    "Iseyin",
    "Mubi",
    "Onitsha",
    "Sagamu",
    "Makurdi",
    "Mokwa",
    "Badagry",
    "Ilesa",
    "Gombe",
    "Obafemi Owode",
    "Owo",
    "Suleja",
    "Lavun",
    "Potiskum",
    "Kukawa",
    "Gusau",
    "Iwo",
    "Bida",
    "Ugep",
    "Ijebu Ode",
    "Epe",
    "Ise Ekiti",
    "Gboko",
    "Ilawe Ekiti",
    "Ikare",
    "Osogbo",
    "Okpoko",
    "Garki",
    "Sapele",
    "Ila",
    "Shaki",
    "Ijero",
    "Ikot Ekpene",
    "Jalingo",
    "Otukpo",
    "Okigwe",
    "Kisi",
    "Buguma",
    "Funtua",
    "Abakaliki",
    "Asaba",
    "Gbongan",
    "Igboho",
    "Gashua",
    "Bama",
    "Uromi",
  ],
  Angola: [
    "Alto Cauale",
    "Alto Zambeze",
    "Ambaca",
    "Ambriz",
    "Ambuila",
    "Andulo",
    "Baía Farta",
    "Bailundo",
    "Balombo",
    "Benguela",
    "Bibala ",
    "Biula",
    "Bungo",
    "Caála ",
    "Cabamba",
    "Cabinda ",
    "Caboledo",
    "Cacolo",
    "Caconda",
    "Cacondá",
    "Caculama",
    "Cacuso",
    "Cafunfo",
    "Cahama",
    "Caiengue",
    "Caimbambo",
    "Calandala",
    "Calenga ",
    "Calonda",
    "Calucinga",
    "Calulo",
    "Caluquembe ",
    "Camabatela",
    "Camacupa ",
    "Camanongue",
    "Camaxilo",
    "Cambambe",
    "Cambongue",
    "Cambundi ",
    "Camissombo",
    "Candjimbe",
    "Cangamba ",
    "Cangandala",
    "Cangumbe",
    "Capelongo",
    "Capenda Camulemba",
    "Capulo",
    "Cassanguide ",
    "Cassongue",
    "Catabola ",
    "Catacanha",
    "Catchiungo ",
    "Catumbela",
    "Caungula",
    "Caxita Cameia",
    "Caxito",
    "Cazaje (Cazage)",
    "Cazombo",
    "Cela",
    "Chiange ",
    "Chibanda",
    "Chibemba",
    "Chibia",
    "Chicala",
    "Chingufo",
    "Chipindo",
    "Chissamba",
    "Chitado",
    "Chitembo",
    "Coemba",
    "Colui ",
    "Conda",
    "Cota",
    "Coutada",
    "Cuangar",
    "Cuango-Luzamba ",
    "Cuasa",
    "Cubal",
    "Cuchi",
    "Cuilo",
    "Cuima",
    "Cuimba",
    "Cuito Cuanavale",
    "Cuvelai",
    "Dala",
    "Damba",
    "Didimbo",
    "Dombe Grande",
    "Dondo",
    "Dongo",
    "Dundo ",
    "Ekunha ",
    "Folgares",
    "Funda",
    "Gabela",
    "Galo",
    "Ganda",
    "Golungo Alto",
    "Guri",
    "Huambo ",
    "Humpata",
    "Jamba",
    "Jamba",
    "Kuito ",
    "Lândana ",
    "Leúa",
    "Lobito",
    "Lombe",
    "Longa",
    "Longonjo",
    "Luacano",
    "Luanda ",
    "Luau",
    "Lubango",
    "Lucala",
    "Lucapa",
    "Lucusse",
    "Luena",
    "Luiana",
    "Luimbale ",
    "Luma Cassao",
    "Lumbala N'guimbo ",
    "Lumeje",
    "Luremo",
    "Luxanraigoto",
    "Luxilo",
    "M'Bimbi ",
    "Malanje ",
    "Malembo",
    "Maludi",
    "Marimba",
    "Marimbanguengo",
    "Massango",
    "Matala",
    "Mavinga",
    "Mbanza-Congo ",
    "Menongue ",
    "Moçâmedes",
    "Muchinda",
    "Muconda ",
    "Mucumbo",
    "Mucusso",
    "Mucussueje",
    "Muginga",
    "Mulondo",
    "Mungo",
    "Munhango",
    "Mussende",
    "Musserra ",
    "Mussuco",
    "N'dalatando ",
    "N'zeto ",
    "Namacunde ",
    "Negage",
    "Nharea",
    "Nóqui",
    "Nzagi ",
    "Ondjiva",
    "Pinheiro",
    "Porto Amboim",
    "Quela",
    "Quibala",
    "Quibaxe",
    "Quicombo ",
    "Quilengues",
    "Quimavongo",
    "Quimbango",
    "Quimbele",
    "Quipungo",
    "Quirima",
    "Sacomar",
    "Samunona",
    "Saurimo",
    "Savate ",
    "Savungo",
    "Songo",
    "Soyo ",
    "Sumbe ",
    "Tchindjenje ",
    "Tchipelongo",
    "Techamutete ",
    "Tentativa",
    "Tombua ",
    "Tumba",
    "Uíge ",
    "Uku ",
    "Ukuma ",
    "Viana",
    "Waku Kungo ",
    "Xá-Muteba",
    "Xangongo ",
  ],
  Algeria: [
    "Ain Oussara",
    "Algiers",
    "Oran",
    "Constantine",
    "Annaba",
    "Blida",
    "Batna",
    "Djelfa",
    "Sétif",
    "Sidi bel Abbès",
    "Biskra",
    "Tébessa",
    "Skikda",
    "Tiaret",
    "Béjaïa",
    "Tlemcen",
    "Béchar",
    "Mostaganem",
    "Bordj Bou Arreridj",
    "Chlef",
    "Souk Ahras",
    "El Eulma",
    "Médéa",
    "Tizi Ouzou",
    "Jijel",
    "Laghouat",
    "El Oued",
    "Ouargla",
    "M'Sila",
    "Relizane",
    "Saïda",
    "Bou Saâda",
    "Guelma",
    "Aïn Beïda",
    "Maghnia",
    "Mascara",
    "Khenchela",
    "Barika",
    "Messaad",
    "Aflou",
  ],
  Ethiopia: [
    "Addis Ababa",
    "Dire Dawa",
    "Mekelle",
    "Adama",
    "Awassa",
    "Bahir Dar",
    "Gonder",
    "Dessie",
    "Jimma",
    "Jijiga",
    "Shashamane",
    "Bishoftu",
    "Sodo",
    "Arba Minch",
    "Hosaena",
    "Harar",
    "Dilla",
    "Nekemte",
    "Debre Birhan",
    "Asella",
    "Debre Mark'os",
    "Kombolcha",
    "Debre Tabor",
    "Adigrat",
    "Areka",
    "Weldiya",
    "Sebeta",
    "Burayu",
    "Shire (Inda Selassie)",
    "Ambo",
    "Arsi Negele",
    "Aksum",
    "Gambela",
    "Bale Robe",
    "Butajira",
    "Batu",
    "Boditi",
    "Adwa",
    "Yirgalem",
    "Waliso",
    "Welkite",
    "Gode",
    "Meki",
    "Negele Borana",
    "Alaba Kulito",
    "Alamata",
    "Chiro",
    "Tepi",
    "Durame",
    "Goba",
    "Assosa",
    "Gimbi",
    "Wukro",
    "Haramaya",
    "Mizan Teferi",
    "Sawla",
    "Mojo",
    "Dembi Dolo",
  ],
  Egypt: [
    "Banha",
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El Kheima",
    "El Mahalla El Kubra",
    "Port Said",
    "Suez",
    "Mansoura",
    "Tanta",
    "Asyut",
    "Faiyum",
    "Zagazig",
    "Ismailia",
    "Aswan",
    "Damanhur",
    "Damietta",
    "Minya",
    "Beni Suef",
    "Luxor",
    "Shibin El Kom",
    "Sohag",
    "Qena",
    "Hurghada",
    "Arish",
  ],
  "South Africa": [
    "Johannesburg",
    "Soweto",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Mitchell's Plain",
    "Umlazi",
    "Katlehong",
    "Tembisa",
    "Khayelitsha",
    "Soshanguve",
    "Mamelodi",
    "Ibhayi",
    "Port Elisabeth",
    "Tshivhase",
    "Pietermaritzburg",
    "Sebokeng",
    "Bloemfontein",
    "Mabopane",
    "Chatsworth",
    "East London",
    "Nelspruit",
    "Kimberley",
    "Upington",
    "Polokwame",
  ],
  Zimbabwe: [
    "Harare",
    "Bulawayo",
    "Chitungwiza",
    "Mutare",
    "Epworth",
    "Gweru",
    "Kwekwe",
    "Kadoma",
    "Masvingo",
    "Chinhoyi",
    "Norton",
    "Marondera",
    "Ruwa",
    "Chegutu",
    "Zvishavane",
    "Bindura",
    "Beitbridge",
    "Redcliff",
    "Victoria Falls",
    "Hwange",
    "Rusape",
    "Chiredzi",
    "Kariba",
    "Karoi",
    "Chipinge",
    "Gokwe",
    "Shurugwi",
  ],
  Tunisia: [
    "Tunis",
    "Ariana",
    "Ben Arous",
    "Manouba",
    "Nabeul",
    "Zaghouan",
    "Bizerte",
    "Béja",
    "Jendouba",
    "Kef",
    "Siliana",
    "Sousse",
    "Monastir",
    "Mahdia",
    "Sfax",
    "Kairouan",
    "Kesserine",
    "Sidi Bouzid",
    "Gabès",
    "Mednine",
    "Tataouine",
    "Gafsa",
    "Tozeur",
    "Kebili",
  ],
  "Cabo Verde": [
    "Praia",
    "Mindelo",
    "Espargos",
    "Assomada",
    "Pedra Badejo",
    "Porto Novo",
    "São Filipe",
    "Tarrafal",
    "Santa Maria",
    "Sal Rei",
    "Mosteiros ",
    "Tarrafal de São Nicolau",
    "Calheta de São Miguel",
    "Porto Inglês ",
    "São Domingos ",
    "Ribeira Grande ",
    "Ponta do Sol",
    "Ribeira Brava",
    "Nova Sintra",
    "Pombas",
    "Cova Figueira",
    "Cidade Velha ",
    "Picos ",
    "João Teves",
  ],
  Chad: [
    "Abéché ",
    "Abou-Deïa ",
    "Adé ",
    "Adré ",
    "Am Dam ",
    "Amdjarass ",
    "Am Timan ",
    "Aouzou ",
    "Arada ",
    "Ati ",
    "Baïbokoum ",
    "Bardaï ",
    "Bébédjia ",
    "Béboto ",
    "Beinamar ",
    "Bénoye",
    "Béré ",
    "Biltine",
    "Bitkine ",
    "Bokoro ",
    "Bol",
    "Bongor ",
    "Bousso ",
    "Djédaa ",
    "Doba",
    "Dourbali ",
    "Fada",
    "Faya-Largeau",
    "Fianga ",
    "Gaoui ",
    "Goré ",
    "Goundi (",
    "Gounou Gaya ",
    "Goz Beïda ",
    "Guélengdeng",
    "Guéréda ",
    "Haraze ",
    "Iriba ",
    "Kélo",
    "Koro Toro ",
  ],
  Namibia: [
    "Keetmanshoop",
    "Windhoek",
    "Walvis Bay",
    "Swakopmund",
    "Henties Bay",
    "Omaruru",
    "Otjiwarongo",
    "Okahandja",
    "Grootfontein",
    "Mariental",
    "Outjo",
    "Gobabis",
    "Tsumeb",
  ],
  Kenya: [
    " Nairobi",
    " Mombasa",
    "Nakuru",
    "Ruiru",
    "Eldoret",
    "Kisumu",
    "Kikuyu",
    "Ngong",
    "Mavoko",
    "Thika",
    "Naivasha",
    "Karuri",
    "Juja",
    "Kitengela",
    "Kiambu",
    "Malindi",
    "Mandera",
    "Kisii",
    "Kakamega",
    "Mtwapa",
    "Wajir",
    "Lodwar",
    "Limuru",
    "Meru",
    "Nyeri",
    "Isiolo",
    "Ukunda",
    "Kiserian",
    "Kilifi",
    "Nanyuki",
    "Busia",
    "Migori",
    "Bungoma",
    "Narok",
    "Embu",
    "Machakos",
    "El Wak",
    "Gilgil",
    "Kimilili",
    "Kericho",
    "Voi",
    "Wanguru",
    "Habaswein",
    "Turi",
    "Moyale",
    "Homa Bay",
    "Kenol",
    "Masalani",
    "Muranga",
    "Webuye",
    "Njoro",
    "Kapsabet",
    "Mumias",
    "Kerugoya-Kutus",
    "Nyahururu",
    "Marsabit",
    "Rhamu",
    "Siaya",
    "Mariakani",
    "Maralal",
    "Mairo-Inya",
    "Kitui",
    "Makutano",
    "Elburgon",
    "Watamu",
    "Lamu",
    "Kajiado",
    "Nyamira",
    "Isebania",
    "Karatina",
    "Kakuma",
    "Lafey",
    "Bondo",
    "Kabarnet",
    "Chuka",
    "Kehancha",
    "Maua",
    "Taveta",
    "Takaba",
    "Eldama Ravine",
    "Hola",
    "Mai Mahiu",
    "Rongo",
    "Oyugis",
    "Wote",
    "Emali",
    "Garbatula",
    "Mbale",
    "Mwingi",
    "Awendo",
    "Kiminini",
    "Moi's Bridge",
    "Mazeras",
    "Malaba",
    "Makindu",
    "Banissa",
    "Msambweni",
    "Namanga",
    "Mbita",
    "Isinya",
  ],
  Togo: [
    "Lomé",
    "Sokodé",
    "Kara",
    "Kpalimé",
    "Atakpamé",
    "Bassar",
    "Tsévié",
    "Aného",
    "Mango",
    "Dapaong",
    "Tchamba",
    "Niamtougou",
    "Bafilo",
    "Notsé",
    "Sotouboua",
    "Vogan",
    "Badou",
    "Biankouri",
    "Tabligbo",
    "Kandé",
    "Amlamé",
    "Galangachi",
    "Kpagouda",
  ],
  Gambia: [
    "Abuko",
    "Bakau",
    "Banjul",
    "Banjulunding",
    "Bansang",
    "Basse Santa Su",
    "Brikama",
    "Brufut",
    "Busumbala",
    "Farafenni",
    "Farato (West Coast)",
    "Gimara Bakadaji",
    "Gunjur",
    "Janjanbureh (Georgetown)",
    "Jufureh",
    "Kalagi",
    "Kanilai",
    "Kerewan",
    "Kololi",
    "Kotu",
    "Kuntaur",
    "Lamin (North Bank Division)",
    "Lamin (Western Division)",
    "Manjai Kunda",
    "Mansa Konko",
    "Nema Kunku",
    "Serekunda",
    "Soma",
    "Sukuta",
    "Tabokoto",
    "Tanji",
    "Yundum",
  ],
  Uganda: [
    "Kampala",
    "Nansana",
    "Kira",
    "Ssabagabo",
    "Mbarara",
    "Mukono",
    "Njeru",
    "Gulu",
    "Lugazi",
    "Masaka",
    "Kasese",
    "Hoima",
    "Lira",
    "Mityana",
    "Mubende",
    "Masindi",
    "Mbale",
    "Jinja",
    "Entebbe",
    "Kitgum",
  ],
  Senegal: [
    "Kanel",
    "Dakar",
    "Touba",
    "Thiès",
    "Rufisque",
    "Kaolack",
    "M'Bour",
    "Ziguinchor",
    "Saint-Louis",
    "Diourbel",
    "Louga",
    "Tambacounda",
    "Richard Toll",
    "Kolda",
    "Mbacké",
    "Tivaouane",
    "Joal-Fadiouth",
    "Kaffrine",
    "Dahra",
    "Bignona",
    "Fatick",
    "Dagana",
    "Bambey",
    "Vélingara",
    "Sédhiou",
    "Sébikhotane",
    "Kédougou",
    "Nguékhokh",
    "Kayar",
    "Pout",
    "Mékhé",
    "Matam",
    "Ouro Sogui",
    "Nioro du Rip",
    "Kébémer",
    "Koungheul",
    "Guinguinéo",
    "Bakel",
    "Mboro",
    "Linguère",
    "Sokone",
    "Goudomp",
    "Thiadiaye",
    "Ndioum",
    "Diamniadio",
    "Khombole",
    "Gossas",
    "Kanel",
  ],
  Morocco: [
    "Casablanca",
    "Fez",
    "Tangier",
    "Marrakesh",
    "Salé",
    "Meknes",
    "Rabat",
    "Oujda",
    "Kenitra",
    "Agadir",
    "Tetouan",
    "Temara",
    "Safi",
    "Mohammedia",
    "Khouribga",
    "El Jadida",
    "Beni Mellal",
    "Aït Melloul",
    "Nador",
    "Dar Bouazza",
    "Taza",
    "Settat",
    "Berrechid",
    "Khemisset",
    "Inezgane",
    "Ksar El Kebir",
    "Larache",
    "Guelmim",
    "Khenifra",
    "Berkane",
    "Taourirt",
    "Bouskoura",
    "Fquih Ben Salah",
    "Dcheira El Jihadia",
    "Oued Zem",
    "El Kelaa Des Sraghna",
    "Sidi Slimane",
    "Errachidia",
    "Guercif",
    "Oulad Teima",
    "Ben Guerir",
    "Tifelt",
    "Lqliaa",
    "Taroudant",
    "Sefrou",
    "Essaouira",
    "Fnideq",
    "Sidi Kacem",
    "Tiznit",
    "Tan-Tan",
    "Ouarzazate",
    "Souk El Arbaa",
    "Youssoufia",
    "Lahraouyine",
    "Martil",
    "Ain Harrouda",
    "Suq as-Sabt Awlad an-Nama",
    "Skhirat",
    "Ouazzane",
    "Benslimane",
    "Al Hoceima",
    "Beni Ansar",
    "M'diq",
    "Sidi Bennour",
    "Midelt",
    "Azrou",
    "Drargua",
  ],
  Cameroon: [
    "Kumba",
    "Nkongsamba",
    "Bafoussam",
    "Bemenda",
    "Garoua",
    "Maroua",
    "Douala",
    "Yaounde",
    "Buea",
    "Ngaoundere",
    "Kausseri",
    "Bertoua",
    "Limbe",
    "Edea",
    "Ebolowa",
    "Loum",
    "Batouri",
    "Mbouda",
    "Kumbo",
    "Dschang",
    "Foumban",
    "Guider",
    "Bali",
    "Bangante",
    "Sangmelima",
    "Mokolo",
    "Founbot",
    "Yagoua",
    "Wum",
    "Meiganga",
    "Tiko",
    "Obala",
    "Kaele",
    "Bandjoun",
    "Muyuka",
    "Bazou",
    "Nguti",
  ],
  Tanzania: [
    "Dar es Salaam",
    "Nansio",
    "Mwanza",
    "Arusha",
    "Dodoma",
    "Mbeya",
    "Morogoro",
    "Tanga",
    "Kahama",
    "Tabora",
    "Zanzibar City",
    "Kigoma",
    "Sumbawanga",
    "Kasulu",
    "Songea",
    "Moshi",
    "Musoma",
    "Shinyanga",
    "Iringa",
    "Singida",
    "Njombe",
    "Bukoba",
    "Kibaha",
    "Mtwara",
    "Mpanda",
    "Tunduma",
    "Makambako",
    "Babati",
    "Handeni",
    "Lindi",
    "Korogwe",
    "Mafinga",
    "Nansio",
  ],
  "Côte d'Ivoire": [
    "Abidjan",
    "Bouaké",
    "Daloa",
    "Yamoussoukro",
    "San-Pédro",
    "Divo",
    "Korhogo",
    "Anyama",
    "Abengourou",
    "Man",
    "Gagnoa",
    "Soubré",
    "Agboville",
    "Dabou",
    "Grand-Bassam",
    "Bouaflé",
    "Issia",
    "Sinfra",
    "Katiola",
    "Bingerville",
    "Adzopé",
    "Séguéla",
    "Bondoukou",
    "Oumé",
    "Ferkessedougou",
    "Dimbokro",
    "Odienné",
    "Duékoué",
    "Danané",
    "Tingréla",
    "Guiglo",
    "Boundiali",
    "Agnibilékrou",
    "Daoukro",
    "Vavoua",
    "Zuénoula",
    "Tiassalé",
    "Toumodi",
    "Akoupé",
    "Lakota",
  ],
  "Dr Congo": [
    "Bandundu",
    "Beni",
    "Boende",
    "Boma",
    "Bukavu",
    "Bunia",
    "Buta",
    "Butembo",
    "Gbadolite",
    "Gemena",
    "Goma",
    "Inongo",
    "Isiro",
    "Kabinda",
    "Kalemie",
    "Kamina",
    "Kananga",
    "Kenge",
    "Kikwit",
    "Kindu",
    "Kinshasa",
    "Kisangani",
    "Kolwezi",
    "Likasi",
    "Lisala",
    "Lubumbashi",
    "Lusambo",
    "Matadi",
    "Mbandaka",
    "Mbuji-Mayi",
    "Mwene-Ditu",
    "Tshikapa",
    "Zongo",
  ],
  Sudan: [
    "Abekr",
    "Abyei",
    "Al Fashir",
    "Al Managil",
    "Al Qadarif",
    "Al-Ubayyid",
    "Atbara",
    "Babanusa",
    "Bentiu",
    "Berber",
    "Buwaidhaa",
    "Delgo",
    "Dongola",
    "Ad-Damazin",
    "Ed Dueim",
    "El Ait",
    "El Gebir",
    "En Nahud",
    "Er Rahad",
    "Geneina",
    "Hala'ib",
    "`Iyāl Bakhīt",
    "Kaduqli",
    "Kassala",
    "Khartoum - Capital",
    "Khartoum North or Bahri",
    "Kusti or Kosti",
    "Malakal",
    "Malualkon",
    "Muglad",
    "Nebelat el Hagana",
    "New Halfa or Halfa Aljadeda",
    "Nimule",
    "Nyala",
    "Omdurman",
    "Port Sudan or Bur Sudan",
    "Rabak",
    "Ruaba or Umm Rawaba",
    "Sennar or Sannar",
    "Shendi or Shandi",
    "Sindscha",
    "Singa",
    "Suakin",
    "Tabat or Al Shaikh Abdulmahmood",
    "Taiyara",
    "Tonj",
    "Wad Banda",
    "Wad Madani or Wad Medani",
    "Wadi Halfa",
    "Umm Bel",
    "Umm Dam",
    "Umm Debbi",
    "Umm Gafala",
    "Umm Keddada",
    "Umm Qantur",
    "Umm Saiyala",
    "Umm Shanqa",
  ],
  Mozambique: [
    "Matola",
    "Maputo",
    "Nampula",
    "Beira",
    "Chimoio",
    "Quelimane",
    "Tete",
    "Nacala",
    "Lichinga",
    "Pemba",
    "Mocuba",
    "Gurúè",
    "Xai-Xai",
    "Maxixe",
    "Angoche",
    "Inhambane",
    "Cuamba",
  ],
  Madagascar: [
    "Antananarivo",
    "Antsirabe",
    "Fianarantsoa",
    "Antsiranana",
    "Mahajanga",
    "Toamasina",
    "Toliara",
    "Sambava",
    "Taolagnaro",
    "Hell-Ville",
    "Antanifotsy",
    "Farafagana",
    "Betafo",
    "Fenoarivo",
    "Ihosy",
    "Antalaha",
    "Ambatolampy",
    "Ambanja",
    "Avironimamo",
    "Maevatanana",
    "Miarinarivo",
    "Amparafaravola",
    "Ambositra",
    "Antsohihy",
    "Maintirano",
    "Ambalavao",
    "Manakara",
    "Vavatenina",
    "Morondava",
    "Tsaratanana",
    "Mananjary",
    "Moramanga",
    "\nMarovoay",
    "Soavinandriana",
    "Mahanoro",
    "Ambatondrazaka",
    "Mananara Avaratra",
    "Andapa",
    "Fandriana",
    "Belo Tsiribihina",
    "Manjakandriana",
    "Faratsiho",
    "Betioky",
    "Ikongo",
    "\nSoanierana - Ivongo",
    "Mananjary",
    "Nosy-Varika",
    "\nTsiombe",
    "Anjozorobe",
    "\nTsiroanomandidy",
    "\nAnkazobe",
  ],
  Niger: [
    "Torodi",
    "Zinder",
    "Abala",
    "Abalak",
    "Agadez",
    "Aguié",
    "Arlit",
    "Ayourou",
    "Balléyara",
    "Birni Ngaouré",
    "Birni Nkonni",
    "Bouza",
    "Dakoro",
    "Diffa",
    "Dogondoutchi",
    "Dosso",
    "Filingué",
    "Gaya",
    "Gazaoua",
    "Gouré",
    "Guidanroumdji",
    "Illéla",
    "Keita",
    "Kollo",
    "Madaoua",
    "Madarounfa",
    "Magaria",
    "Maïné-Soroa",
    "Maradi",
    "Matameye",
    "Mayahi",
    "Mirriah",
    "Nguigmi",
    "Niamey",
    "Ouallam",
    "Say",
    "Tahoua",
    "Tânout",
    "Tchintabaraden",
    "Téra",
    "Tessaoua",
    "Tibiri",
    "Tillabéri",
  ],
  "Burkina Faso": [
    "Aribinda",
    "Bagré",
    "Banfora",
    "Batié",
    "Bobo Dioulasso",
    "Bogandé",
    "Bondigui",
    "Boromo",
    "Boulsa",
    "Boussé",
    "Dano",
    "Dédougou",
    "Diapaga",
    "Diébougou",
    "Djibo",
    "Dori",
    "Fada N'gourma",
    "Gaoua",
    "Garango",
    "Gayéri",
    "Gorom-Gorom",
    "Gourcy",
    "Houndé",
    "Kampti",
    "Kantchari",
    "Kaya",
    "Kindi",
    "Kokologo",
    "Kombissiri",
    "Kongoussi",
    "Kordié",
    "Koudougou",
    "Kouka, Bam",
    "Kouka, Banwa",
    "Koupéla",
    "Léo",
    "Loropeni",
    "Manga",
    "Méguet",
    "Mogtedo",
    "Niangoloko",
    "Nouna",
    "Orodara",
    "Ouagadougou ",
    "Ouahigouya",
    "Ouargaye",
    "Pama",
    "Pissila",
    "Pô",
    "Pouytenga",
    "Réo",
    "Saponé",
    "Sapouy",
    "Sebba",
    "Séguénéga",
    "Sindou",
    "Solenzo",
    "Tangin Dassouri",
    "Tenkodogo",
    "Tikaré",
    "Titao",
    "Toma",
    "Tougan",
    "Villy",
    "Yako",
    "Ziniaré",
    "Zorgo",
  ],
  Mali: [
    "Ouelesse-bougou",
    "Bamako",
    "Sikasso",
    "Kalabancoro",
    "Koutiala",
    "Ségou",
    "Kayes",
    "Kati",
    "Mopti",
    "Niono",
    "Gao",
    "San",
    "Koro",
    "Bla",
    "Bougouni",
    "Mandé",
    "Baguineda-",
    "Camp",
    "Kolondiéba",
    "Kolokani",
    "Pelengana",
    "Timbuktu",
    "Koury",
    "Massigui",
    "Tonka",
    "Kadiolo",
    "Wassoulou-",
    "Balle",
    "Kaladougou",
    "Koumantou",
  ],
  Zambia: [
    " Lusaka",
    "Kitwe",
    "Ndola",
    "Kabwe",
    "Chingola",
    "Mufulira",
    "Livingstone",
    " Luanshya",
    "Chipata",
    "Kasama",
    " Solwezi",
    "Mansa",
    "Chililabombwe",
    " Mazabuka",
    "Kafue",
    " Kalulushi",
    "Choma",
    "Mongu",
    "Kapiri Mposhi",
    "Nakonde",
  ],
  Somalia: [
    "Borama          ",
    "Lughaye         ",
    "Zeylac          ",
    "Ceel Barde      ",
    "Rab Dhuure      ",
    "Tayeeglow       ",
    "Waajid          ",
    "Xudur           ",
    "Banadir         ",
    "Bandarbayla     ",
    "Bossaso         ",
    "Caluula         ",
    "Iskushuban      ",
    "Qandala         ",
    "Qardho          ",
    "Baidoa          ",
    "Buur Hakaba     ",
    "Diinsoor        ",
    "Qansax Dheere   ",
    "Leego",
    "Baardheere      ",
    "Belet Xaawo     ",
    "Ceel Waaq       ",
    "Doolow          ",
    "Garbahaarey     ",
    "Luuq            ",
    "Cabudwaaq       ",
    "Cadaado         ",
    "Ceel Buur       ",
    "Ceel Dheer      ",
    "Dhuusamarreeb   ",
    "Belet Weyne     ",
    "Bulo Burto      ",
    "Buq Aqable",
    "ceelcali",
    "Jalalaqsi       ",
    "Mataban",
    "moqakori",
    "Afmadow      ",
    "Badhaadhe    ",
    "Jamaame      ",
    "Kismayo      ",
    "Xagar",
    "Afgooye   ",
    "Baraawe",
    "Kurtunwaarey",
    "Marka   ",
    "Qoryooley",
    "Wanla Weyn  ",
    "Sablaale",
    "Bu'aale         ",
    "Jilib           ",
    "Saakow          ",
    "Adan Yabaal     ",
    "Balcad          ",
    "Cadale          ",
    "Jowhar          ",
    "Mahadaay",
    "Warsheekh",
    "Gaalkacyo       ",
    "Galdogob        ",
    "Hobyo           ",
    "Jariiban        ",
    "Xarardheere     ",
    "Burtinle        ",
    "Eyl             ",
    "Garowe          ",
    "Badhan",
    "Xingalool     ",
    "Ceerigaabo      ",
    "Dhahar",
    "Laasqoray       ",
    "Caynabo         ",
    "Boocame",
    "Laas Caanood    ",
    "Taleex          ",
    "Burco           ",
    "Buuhoodle       ",
    "Owdweyne        ",
    "Sheikh          ",
    "Berbera         ",
    "Gebiley         ",
    "Hargeysa        ",
    "Salahlay",
  ],
  Guinea: [
    "Beyla",
    "Boffa",
    "Boké",
    "Conakry ",
    "Coyah",
    "Dabola",
    "Dalaba",
    "Dinguiraye",
    "Dubréka",
    "Faranah",
    "Forécariah",
    "Fria",
    "Gaoual",
    "Guéckédou",
    "Kankan",
    "Kérouané",
    "Kindia",
    "Kissidougou",
    "Koubia",
    "Koundara",
    "Kouroussa",
    "Labé",
    "Lélouma",
    "Lola",
    "Macenta",
    "Mandiana",
    "Mali",
    "Mamou",
    "Nzérékoré",
    "Pita",
    "Siguiri",
    "Télimélé",
    "Timbo",
    "Tougué",
    "Yomou",
    "Wheek",
  ],
  Rwanda: [
    "Rubengera",
    "Kigali",
    "Gisenyi",
    "Ruhengeri",
    "Butare",
    "Muhanga",
    "Byumba",
    "Cyangugu",
    "Nyanza",
    "Bugarama",
    "Kayonza",
    "Rwamagana",
    "Nyamata",
    "Ruhango",
    "Gikongoro",
    "Nyagatare",
    "Busogo",
    "Kibuye",
    "Kibungo",
  ],
  Benin: [
    "Abomey",
    "Abomey-Calavi",
    "Athiémè",
    "Banikoara",
    "Bassila",
    "Bembèrèkè",
    "Bétérou",
    "Bohicon",
    "Bori",
    "Boukoumbé",
    "Comè",
    "Cotonou",
    "Cové",
    "Dassa-Zoumé",
    "Djougou",
    "Dogbo-Tota",
    "Founougo",
    "Ganvie",
    "Godomey",
    "Grand-Popo",
    "Guénè",
    "Kandi",
    "Kérou",
    "Kétou",
    "Kouandé",
    "Lokossa",
    "Malanville",
    "Natitingou",
    "Ndali",
    "Nikki",
    "Ouidah",
    "Parakou",
    "Péhonko",
    "Pobè",
    "Porga",
    "Sakété",
    "Sam",
    "Savalou",
    "Savé",
    "Ségbana",
    "Tanguiéta",
    "Tchaourou",
    "Toura",
  ],
  Burundi: [
    "Bubanza",
    "Buhongo",
    "Bujumbura ",
    "Bukirasazi",
    "Bururi",
    "Cankuzo",
    "Cibitoke",
    "Gitega ",
    "Kabezi",
    "Karuzi",
    "Kayanza",
    "Kayero",
    "Kayogoro",
    "Kibondo",
    "Kirundo",
    "Kisozi",
    "Luhwa",
    "Makamba",
    "Magara",
    "Mukenke",
    "Muramvya",
    "Murore",
    "Musenyi",
    "Muyaga",
    "Muyinga",
    "Mwaro",
    "Ngozi",
    "Nyanza-Lac",
    "Rugari",
    "Rumonge",
    "Rutana",
    "Ruyigi",
    "Ruzunga",
    "Zanandore",
  ],
  "South Sudan": [
    "Abyei",
    "Akobo",
    "Aweil",
    "Bentiu ",
    "Bor",
    "Gogrial",
    "Juba",
    "Kuajok ",
    "Malakal",
    "Nimule",
    "Pajok",
    "Rumbek",
    "Makol-Chuei",
    "Torit",
    "Wau",
    "Wanyjok ",
    "Yambio",
    "Yei",
    "Yirol",
  ],
  "Sierra Leone": [
    "Wangechi",
    "Kalewa",
    "Magburaka",
    "Kabala",
    "Moyamba",
    "Kailahun",
    "Bonthe",
    "Kambia",
    "Freetown",
    "Kenema",
    " Bo",
    "Koidu",
    "Makeni",
    "Waterloo",
    " Port Loko",
    "Alikalia",
    "Binkolo",
    "Daru",
    "Falaba",
    "Gbinti",
    "Kamakwie",
    "Kaima",
    "Koindu",
    "Lungi",
    "Lunsar",
    "Madina",
    "Mange",
    "Mano",
    "Matru",
    "Momaligi",
    "Njala",
    "Pepel",
    "Pendembu",
    "Shenge",
    "Sulima",
    "Sumbaria",
    "Taiama",
    "Tongo",
    "Tumbu",
    "Worodu",
    "Yana",
    "Yele",
    "Yengema",
    "Yonibana",
  ],
  Libya: [
    "Tripoli ",
    "Benghazi ",
    "Misrata ",
    "Zawiya ",
    "Bayda ",
    "Gharyan ",
    "Tobruk ",
    "Ajdabiya ",
    "Zliten ",
    "Derna ",
    "Sirte ",
    "Sabha ",
    "Khoms ",
    "Bani Walid ",
    "Sabratha ",
    "Zuwara ",
    "Kufra ",
    "Marj ",
    "Tocra ",
    "Tarhuna ",
    "Msallata ",
    "Jumayl ",
    "Sorman ",
    "Al Gseibat",
    "Shahhat ",
    "Ubari ",
    "Asbi'a ",
    "Jadid",
    "Waddan",
    "El Agheila ",
    "Abyar ",
    "Nofaliya ",
    "Regdalin ",
    "Gasr Akhyar",
    "Al Qubah ",
    "Tawergha ",
    "Al Maya",
    "Murzuk ",
    "Brega",
    "Teghsat",
    "Hun",
    "Jalu",
    "Ajaylat",
    "Nalut",
    "Suluq",
    "Shuhada' al Buerat",
    "Zaltan",
    "Mizda",
    "Ra's Lanuf",
    "Al Urban",
    "Yafran",
    "Ar Rayaniya",
    "Umm al Rizam",
    "Taucheira",
    "Brak",
    "Abu Ghlasha",
    "Ad Dawoon",
    "Teji",
    "Qaminis",
    "Qatrun",
    "Benina",
    "Kikla",
    "Al Rheibat",
    "Sokna",
    "Massa",
    "Bin Jawad",
    "Umm al Aranib",
    "Jadu",
    "Ghadames",
    "Ar Rabta",
    "Ghat",
    "Al Abraq",
    "Sidi as Said",
    "Ar Rajban",
    "Awjila",
    "Ras al Hamam",
    "Tolmeita",
    "Zella",
    "Wadi Utba",
    "Al Barkat",
    "Martuba",
    "Traghan",
    "Al Hashan",
    "El Bayyada",
    "Qayqab",
    "Mashashita",
    "Bu-Fakhra",
    "Musaid",
    "Tacnis",
    "Susa",
    "Wadi Zem-Zem",
    "Batta",
    "Tazirbu",
    "Jadid",
    "Farzougha",
    "Qaryat ‘Umar al Mukhtar",
    "Bi'r al Ashhab",
  ],
  Congo: [
    "Brazzaville",
    "Pointe-Noire",
    "Dolisie",
    "Nkayi",
    "Impfondo",
    "Ouésso",
    "Madingou",
    "Owando",
    "Sibiti",
    "Loutété",
    "Bouansa",
    "Gamboma",
    "Mossaka",
    "Mindouli",
    "Oyo",
    "Makoua",
    "Loudima",
    "Mossendjo",
    "Mouyondzi",
    "Bétou",
    "Djambala",
    "Pokola",
    "Ngo",
    "Makabana",
    "Kinkala",
    "Ewo",
    "Etoumbi",
    "Boundji",
    "Dongou",
    "Komono",
    "Kellé",
    "Enyellé",
    "Kindamba",
    "Tchiamba-Nzassi",
    "Ollombo",
    "Loukoléla",
    "Sembé",
    "Mbinda",
    "Zanaga",
    "Lekana",
  ],
  Liberia: [
    "Arthington",
    "Barclayville",
    "Bensonville",
    "Brewerville",
    "Bopolu",
    "Buchanan",
    "Buutuo",
    "Caldwell",
    "Careysburg",
    "Clay-Ashland",
    "Edina",
    "Fish Town",
    "Ganta",
    "Gbarnga",
    "Greenville",
    "Harbel",
    "Harper",
    "Kakata",
    "Monrovia ",
    "Marshall",
    "Paynesville",
    "Pleebo",
    "River Cess",
    "Robertsport",
    "Sacleipea",
    "Sanniquellie",
    "Tubmanburg",
    "Tuzon",
    "Virginia",
    "Voinjama",
    "Yekepa",
    "Zorzor",
    "Zwedru",
  ],
  "Central African Republic": [
    "Alindao",
    "Baboua",
    "Bahamo",
    "Bambari",
    "Bangassou",
    "Bangui",
    "Baoro",
    "Batangafo",
    "Berbérati",
    "Bimbo",
    "Birao",
    "Boali",
    "Bobangui",
    "Boda[10]",
    "Bossangoa",
    "Bossembélé",
    "Bouar",
    "Bouca",
    "Bozoum",
    "Bria",
    "Carnot",
    "Damara",
    "Gambo",
    "Gamboula",
    "Guen",
    "Ippy",
    "Kabo",
    "Kaga-Bandoro",
    "Kembé",
    "Kouango",
    "Mbaïki",
    "Mobaye",
    "Mongoumba",
    "N'Délé",
    "Nola",
    "Obo",
    "Ouadda",
    "Ouango",
    "Paoua",
    "Rafaï[",
    "Sibut",
    "Sikkikede",
    "Zinga",
  ],
  Mauritania: [
    "Nouakchott",
    "Nouadhibou",
    "Kiffa",
    "Mbera Refugee Camp",
    "Kaédi",
    "Zouérat",
    "Rosso",
    "Sélibabi",
    "Boû Gâdoûm",
    "Boutilimit",
    "Atar",
    "Bareina",
    "Ghabou",
    "Hamoud",
    "Mâl",
    "Nbeika",
    "Gouraye",
    "Timbedra",
    "Magta-Lahjar",
    "Guerou",
    "Soudoud",
    "Sélibaby",
    "Foum Gleita",
    "Legceïba",
    "Bousteila",
    "Sangrave",
    "Tintane",
    "Néma",
    "Aleg",
    "Tidjikdja",
    "Oualata",
    "Ayoûn el-Atroûs",
    "Bababé",
    "Akjoujt",
    "Cheggar",
  ],
  Eritrea: [
    "Asmara",
    "Keren",
    "Teseney",
    "Mendefera",
    "Agordat",
    "Assab",
    "Massawa",
    "Adi Quala",
    "Senafe",
    "Dekemhare",
    "Segheneyti",
    "Nakfa",
    "Adi Keyh",
    "Barentu",
    "Beilul",
    "Edd",
    "Ghinda",
    "Mersa Fatuma",
    "Himberti",
    "Nefasit",
    "Adi Tekelezan",
    "Afabet",
    "Areza",
    "Badme",
    "Bisha",
    "Dairo Paulos",
    "Debaysima",
    "Digsa",
    "Emba Derho",
    "Quazien",
    "Filfil",
    "Goquat",
    "Hazega",
    "Kudo-Felasi",
    "Matara",
    "Mai Mine",
    "Mersa Gulbub",
    "Mersa Teklay",
    "Omhajer",
    "Per Tokar",
    "Quatit",
    "Rahayta",
    "Sebderat",
    "Tserona",
    "Tsazega",
    "Zula",
    "Zahgir",
    "Adi-Abeto",
    "Kudofelasi",
    "Molki",
    "Shambuko",
    "Golij",
    "Tara Emni",
    "shakaeyamo",
    "Emni hayli",
    "knafna",
    "Tsorona",
    "Enda gergs",
    "Haykota",
    "Fortosawa",
    "Sh'eb",
    "Ela bered",
    "Adi Qontsi",
    "Meka'ika",
  ],
  Botswana: [
    "Gaborone",
    "Francistown",
    "Mogoditshane",
    "Maun",
    "Molepolole",
    "Serowe",
    "Tlokweng",
    "Palapye",
    "Mochudi",
    "Mahalapye",
    "Kanye",
    "Selibe Phikwe",
    "Letlhakane",
    "Ramotswa",
    "Lobatse",
    "Mmopane",
    "Thamaga",
    "Moshupa",
    "Tonota",
    "Bobonong",
    "Gabane",
    "Ghanzi",
    "Jwaneng",
    "Tutume",
    "Kopong",
    "Mmadinare",
    "Tati Siding",
    "Tshabong",
    "Metsimotlhabe",
    "Gumare",
    "Shakawe",
    "Oodi",
    "Bokaa",
    "Kasane",
    "Borolong",
    "Shoshong",
    "Molapowabojang",
    "Kazungula",
    "Orapa",
    "Letlhakeng",
    "Nata",
    "Rakops",
    "Mmankgodi",
    "Lerala",
    "Otse",
    "Kumakwane",
    "Sese",
    "Kang",
    "Lentsweletau",
    "Ramotswa station/Taung",
    "Masunga",
    "Lotlhakane",
    "Sefophe",
    "Rasesa",
    "Maitengwe",
    "Mathangwane",
    "Shashe-Mooke",
    "Good Hope",
    "Gweta",
    "Mmathethe",
    "Sefhare",
    "Chadibe",
    "Tsetsebjwe",
    "Hukuntsi",
    "Charles Hill",
    "Morwa",
    "Mandunyane",
    "Etsha 6",
    "Digawana",
    "Mokatse",
    "Pitsane Siding",
    "Mopipi",
    "Dukwi",
    "Nkange",
    "Matshelagabedi",
    "Ramokgonami",
    "Sebina",
    "Maunatlala",
    "Shashe",
    "Manyana",
    "Chadibe",
    "Modipane",
    "Takatokwane",
    "Etsha 13",
    "Lecheng",
    "Werda",
    "Moiyabana",
    "Gakuto",
    "Pilane Station",
    "Ranaka",
    "Matebeleng",
    "Radisele",
    "Khudumelapye",
    "Khakhea",
    "Serule",
    "Matlapana",
    "Mogorosi",
    "Tobane",
    "Mookane",
    "Mmashoro",
    "Thebephatshwa Air Base (BDFCamp)",
    "Mogobane",
    "Sowa",
    "Thabala",
    "Ntlhantlhe",
    "Dekar",
    "Malolwane",
    "Seronga",
    "Machaneng",
    "Pandamatenga",
    "Paje",
    "Molalatau",
    "Sehithwa",
    "Tumasera",
    "Ditshegwane",
    "Salajwe",
    "Mokoboxane",
    "Mathathane",
    "Mmathubudukwane",
    "Nokaneng",
    "Mabutsane",
    "Mohembo West",
    "Marapong",
    "Nshakashokwe",
    "Senete",
    "Artisia",
    "Sojwe",
    "Mabeleapudi",
    "Lesenepole",
    "Mosolotshane",
    "Tshesebe",
    "Matsiloje",
    "Otse",
    "Kalamare",
    "Ratholo",
    "Mokobeng",
    "Ncojane",
    "Nswazwi",
    "Lorolwana",
    "Mogapi",
    "Makobo",
    "Tsamaya",
    "Tsau",
    "Mmatseta",
    "Seleka",
    "Maokane",
    "Sepopa",
    "Mabesekwa",
    "Moletemane",
    "Tshimoyapula",
    "Mosetse",
    "Lotlhakane West",
    "Mokubilo",
    "Xhumo",
    "Lehututu",
    "Sesung",
    "Moroka",
    "Kobojango",
    "Rakhuna",
    "Marobela",
    "Moshaneng",
    "Themashanga",
    "Tsootsha",
    "Gojwane",
    "Kauxwhi",
    "Kudumatse",
    "Malatswai",
    "Mmanoko",
    "Toteng",
    "Mabule",
    "Maboane",
    "Makwate",
    "Lokgwabe",
    "Motlhabaneng",
    "Dimajwe",
    "Makopong",
    "Majwaneng",
    "Zwenshambe",
    "Ditladi",
    "Mogapinyana",
    "Magotlhwane",
    "Selokolela",
    "Lorwana",
    "Motokwe",
    "Mmatshumo",
    "Moshaweng",
    "Mosu",
    "Kokotsha",
    "Kgomokasitwa",
    "Samochema",
    "Goshwe",
    "Natale",
    "Phitshane Molopo",
    "New Xade",
    "Gamodubu",
    "Topisi",
    "Seolwane",
    "Xakao",
    "Kgagodi",
    "Zoroga",
    "Makalamabedi",
    "Kodibeleng",
    "Ramatlabama",
    "Tshokwe",
    "Mafongo",
    "Sikwane",
    "Ramokgwebana",
    "Kedia",
    "Etsha 1",
    "Matobo",
    "Nlakhwane",
    "Damochojena",
    "Pitseng",
    "Khwee",
    "Matsitama",
    "Beetsha",
    "Nxamasere",
    "Semolale",
    "Botlhapatlou",
    "Senyawe",
    "Sekoma",
    "Dutlwe",
    "Makaleng",
    "Mapoka",
    "Gootau",
    "Tamasane",
    "Malwelwe",
    "Phepheng",
    "Boatlaname",
    "Dibete Station",
    "Kutamogree",
    "Dinokwe",
    "Borotsi",
    "Jackalas 2",
    "Sorilatholo",
    "Siviya",
    "Kareng",
    "Jackalas 1",
    "Pilikwe",
    "Mmaphashalala",
    "Ngarange",
    "Lekgolobotlo",
    "Tloaneng",
    "Hatsalatladi",
    "Maape",
    "Moralane",
    "Khawa",
    "Bray",
    "Kaudwane",
    "Sehunou",
    "Shakwe",
    "Motopi",
    "Sekhutlane",
    "Omaweneno",
    "Mokolodi",
    "Motshegaletau",
    "Lesoma",
    "Mabalane",
    "Kuke",
    "Shashe Bridge",
    "Keng",
    "Kachikau",
    "Groote Laagte",
    "Serinane",
    "Matlhakola",
    "Moshopha",
    "Gasita",
    "Mahotshwane",
    "Mulambakwena",
    "Tlhankane",
    "Sepako",
    "Mosojane",
    "Kokong",
    "Leologane",
    "Ngware",
    "Gani",
    "Malaka",
    "West Hanahai",
    "Gathwane",
    "Karakobis",
    "Tshane",
    "Borotsi",
    "Bodibeng",
    "Mogonye",
    "Jamataka",
    "Mogomotho",
    "Mokhomba",
    "Lepokole",
    "Dagwi",
    "Magoriapitse",
    "Mmeya",
    "Qabo",
    "Metlobo",
    "Malotwana Siding",
    "Shorobe",
    "Qangwa",
    "Kumaga",
    "Pitsana-Potokwe",
    "Segwagwa",
    "Dovedale",
    "Chobokwane",
    "Parakarungu",
    "Mmadikola",
    "Mokgenene",
  ],
  Gabon: [
    "Akanda",
    "Akok",
    "Bakoumba",
    "Batouala",
    "Belinga",
    "Bifoun",
    "Bitam",
    "Bongoville",
    "Booué",
    "Cocobeach",
    "Ekata",
    "Étéké",
    "Fougamou",
    "Franceville",
    "Gamba",
    "Kango",
    "Koulamoutou",
    "Lalara",
    "Lambaréné",
    "Lastoursville",
    "Leconi",
    "Libreville ",
    "Makokou",
    "Mayumba",
    "Mbigou",
    "Médouneu",
    "Mékambo",
    "Mimongo",
    "Minvoul",
    "Mitzic",
    "Moanda",
    "Momo",
    "Mouila",
    "Mounana",
    "Ndendé",
    "Ndjolé",
    "Nkan",
    "Nkolabona",
    "Ntoum",
    "Okandja",
    "Omboué ",
    "Owendo",
    "Oyem",
    "Petit Loango",
    "Point Denis",
    "Port-Gentil",
    "Santa Clara",
    "Setté Cama",
    "Ste. Marie",
    "Souba-Haut-Ogooue",
    "Tchibanga",
    "Tsogni",
    "Zoula",
  ],
  Lesotho: [
    "Thaba-Tseka",
    "Maseru",
    "Teyateyaneng",
    "Mafeteng",
    "Hlotse",
    "Mohale's Hoek",
    "Maputsoe",
    "Qacha's Nek",
    "Quthing",
    "Butha-Buthe",
    "Mokhotlong",
  ],
  "Guinea-Bissau": [
    "Bissau",
    "Gabú",
    "Bafatá",
    "Canchungo",
    "Bissorã",
    "Farim",
    "Mansôa",
    "Buba",
    "Cacheu",
    "Quinhámel",
    "Quebo",
    "Catió",
    "Bolama",
  ],
  "Equatorial Guinea": [
    "Bata",
    "Malabo",
    "Ebebiyín",
    "Aconibe",
    "Añisoc",
    "Luba",
    "Evinayong",
    "Mongomo",
    "Mengomeyén",
    "Micomeseng",
    "Rebola",
    "Bidjabidjan",
    "Niefang",
    "Cogo",
    "Nsok",
    "San Antonio de Palé",
    "Mbini",
    "Nsork",
    "Ayene",
    "Nkimi",
    "Machinda",
    "Acurenam",
    "Corisco",
    "Baney",
    "Bicurga",
    "Nsang",
    "Ncue",
    "Bitica",
    "Río Campo",
    "Riaba",
  ],
  Mauritius: [
    "Port Louis",
    "Vacoas-Phoenix",
    "Beau Bassin-Rose Hill",
    "Curepipe",
    "Quatre Bornes",
    "Saint Julien d'Hotman",
    "Ville Bague",
    "Albion",
    "Amaury",
    "Saint Pierre",
    "Amitié-Gokhoola",
    "Anse La Raie",
    "Arsenal",
    "Baie du Cap",
    "Baie du Tombeau",
    "Bambous",
    "Bambous Virieux",
    "Bananes",
    "Beau Vallon",
    "Bel Air Rivière Sèche",
    "Bel Ombre",
    "Belle Vue Haurel",
    "Bénarès",
    "Bois Chéri",
    "Bois des Amourettes",
    "Bon Accueil",
    "Bramsthan",
    "Brisée Verdière",
    "Sébastopol",
    "Britannia",
    "Calebasses",
    "Camp Carol",
    "Camp de Masque",
    "Camp de Masque Pavé",
    "Camp Diable",
    "Camp Ithier",
    "Camp Thorel",
    "Cap Malheureux",
    "Cascavelle",
    "Seizième Mille",
    "Case Noyale",
    "Centre de Flacq",
    "Chamarel",
    "Souillac",
    "Chamouny",
    "Chemin Grenier",
    "Clémencia",
    "Cluny",
    "Congomah",
    "Cottage",
    "Crève Coeur",
    "D'Épinay",
    "Dagotière",
    "Dubreuil",
    "Surinam",
    "Écroignard",
    "Espérance",
    "Espérance Trébuchet",
    "Flic en Flac",
    "Fond du Sac",
    "Goodlands",
    "Grand Baie",
    "Tamarin",
    "Grand Bel Air",
    "Grand Bois",
    "Grand Gaube",
    "Grand Sable",
    "Grande Retraite",
    "Grande Rivière Noire",
    "Grande Rivière Sud Est",
    "Gros Cailloux",
    "L'Avenir",
    "L'Escalier",
    "Terre Rouge",
    "La Flora",
    "Triolet",
    "La Gaulette",
    "La Laura-Malenga",
    "Lalmatie",
    "Laventure",
    "Le Hochet",
    "Le Morne",
    "Le Vale",
    "Mahébourg",
    "Mapou",
    "Trois Boutiques",
    "Mare Chicose",
    "Mare d'Albert",
    "Mare La Chaux",
    "Mare Tabac",
    "Médine Camp de Masque",
    "Trou aux Biches",
    "Melrose",
    "Midlands",
    "Moka",
    "Trou d'Eau Douce",
    "Montagne Blanche",
    "Tyack",
    "Montagne Longue",
    "Morcellement Saint André",
    "New Grove",
    "Notre Dame",
    "Nouvelle Découverte",
    "Nouvelle France",
    "Olivia",
    "Pailles",
    "Pamplemousses",
    "Petit Bel Air",
    "Petit Raffray",
    "Petite Rivière",
    "Piton",
    "Union Park",
    "Plaine des Papayes",
    "Plaine des Roches",
    "Vale",
    "Plaine Magnien",
    "Pointe aux Piments",
    "Poste de Flacq",
    "Poudre d'Or",
    "Poudre d'Or Hamlet",
    "Providence",
    "Quartier Militaire",
    "Quatre Cocos",
    "Quatre Soeurs",
    "Queen Victoria",
    "Richelieu",
    "Ripailles",
    "Verdun",
    "Rivière des Anguilles",
    "Rivière des Créoles",
    "Rivière du Poste",
    "Vieux Grand Port",
    "Rivière du Rempart",
    "Roche Terre",
    "Roches Noires",
    "Rose Belle",
    "Saint Aubin",
    "Saint Hubert",
    "Saint Julien Village",
  ],
  Eswatini: [
    "Manzini",
    "Mbabane",
    "Big Bend",
    "Malkerns",
    "Nhlangano",
    "Mhlume",
    "Hluti",
    "Simunye",
    "Siteki",
    "Piggs Peak",
    "Lobamba",
    "Ngomane",
    "Vuvulane",
    "Mpaka",
    "Kwaluseni",
    "Bhunya",
    "Mhlambanyatsi",
    "Mondi",
    "Tabankulu",
    "Hlatikulu",
    "Bulembu",
    "Kubuta",
    "Tjaneni",
    "Sidvokodvo",
    "Lavumisa",
    "Ngwenya",
    "Nsoko",
    "Mankayane",
  ],
  Djibouti: [
    "Djibouti City ",
    "Ali Sabieh",
    "Dikhil",
    "Tadjoura",
    "Arta",
    "Obock",
    "As Ela ",
    "Assa Hougoud ",
    "Assamo",
    "Balho ",
    "Chebelle ",
    "Daimoli ",
    "Daoudaouya ",
    "Dorale ",
    "Doumera ",
    "Godoria ",
    "Khor Angar ",
    "Randa ",
    "Ras Siyyan ",
    "Sagallou ",
    "Yoboki ",
    "Boul'aos",
  ],
  Comoros: [
    "Moroni",
    "Moutsamoudou",
    "Fomboni",
    "Domoni",
    "Sima",
    "Ouani",
    "Mirontsi",
    "Mkiriwadjumoi",
    "Koni-Djodjo",
    "Moya",
  ],
  "Sao Tome & Principe": [
    "São Tomé (capital)",
    "Santo Amaro",
    "Neves",
    "Santana",
    "Trindade",
    "Santa Cruz",
    "Pantufo",
    "Guadalupe",
    "Santo António",
    "Santa Catarina",
    "Porto Alegre",
    "Bom Successo",
    "Ribeira Afonso",
    "São João dos Angolares",
  ],
  Seychelles: ["Anse Boileau", "Beau Vallon", "Takamaka", "Victoria", "Grand Anse Mahe"],
};

module.exports.currencyAndCode = {
  Algeria: {
    code: 233,
    currency: "DA",
  },
  Angola: {
    code: 213,
    currency: "Kz",
  },
  Botswana: {
    code: 267,
    currency: "P",
  },
  Burundi: {
    code: 257,
    currency: "Fbu",
  },
  "Cabo Verde": {
    code: 238,
    currency: "$",
  },
  Cameroom: {
    code: 237,
    currency: "FCFA",
  },
  "Central African Republic": {
    code: 236,
    currency: "FCFA",
  },
  Chad: {
    code: 235,
    currency: "FCFA",
  },
  Congo: {
    code: 242,
    currency: "FCFA",
  },
  "Equatorial Guinea": {
    code: 240,
    currency: "FCFA",
  },
  Gabon: {
    code: 241,
    currency: "FCFA",
  },
  Benin: {
    code: 229,
    currency: "CFA",
  },
  "Burkina Faso": {
    code: 226,
    currency: "CFA",
  },
  "Guinea-Bissau": {
    code: 245,
    currency: "CFA",
  },
  "Côte d'Ivoire": {
    code: 225,
    currency: "CFA",
  },
  Mali: {
    code: 223,
    currency: "CFA",
  },
  Niger: {
    code: 227,
    currency: "CFA",
  },
  Senegal: {
    code: 221,
    currency: "CFA",
  },
  Togo: {
    code: 228,
    currency: "CFA",
  },
  Comoros: {
    code: 269,
    currency: "FC",
  },
  "Democratic Republic of the Congo": {
    code: 234,
    currency: "FC",
  },
  Gambia: {
    code: 220,
    currency: "DA",
  },
  Djibouti: {
    code: 253,
    currency: "Fji",
  },
  Egypt: {
    code: 20,
    currency: "LE",
  },
  Eritrea: {
    code: 291,
    currency: "Nkf",
  },
  Ethiopia: {
    code: 251,
    currency: "Br",
  },
  Ghana: {
    code: 233,
    currency: "GHS",
  },
  Guinea: {
    code: 224,
    currency: "FG",
  },
  Kenya: {
    code: 254,
    currency: "KSh",
  },
  Lesotho: {
    code: 266,
    currency: "LE",
  },
  Liberia: {
    code: 231,
    currency: "$",
  },
  Libya: {
    code: 218,
    currency: "LD",
  },
  Eswatini: {
    code: 268,
    currency: "L",
  },
  Madagascar: {
    code: 261,
    currency: "Ar",
  },
  Malawi: {
    code: 265,
    currency: "MK",
  },
  Mauritius: {
    code: 230,
    currency: "Re",
  },
  Morroco: {
    code: 212,
    currency: "DH",
  },
  Mozambique: {
    code: 258,
    currency: "Mt",
  },
  Namibia: {
    code: 264,
    currency: "N$",
  },
  Nigeria: {
    code: 234,
    currency: "₦",
  },
  Mauritania: {
    code: 222,
    currency: "UM",
  },
  Zimbabwe: {
    code: 263,
    currency: "$",
  },
  Rwanda: {
    code: 250,
    currency: "FRw",
  },
  "Sao Tome & Principe": {
    code: 239,
    currency: "Db",
  },
  Seychelles: {
    code: 248,
    currency: "Rs",
  },
  Tanzania: {
    code: 255,
    currency: "TSh",
  },
  Uganda: {
    code: 256,
    currency: "Ush",
  },
  Somalia: {
    code: 252,
    currency: "Sh.So",
  },
  "South Sudan": {
    code: 211,
    currency: "£",
  },
  Sudan: {
    code: 249,
    currency: "LS",
  },
  Tunisia: {
    code: 216,
    currency: "DT",
  },
  "South Africa": {
    code: 27,
    currency: "R",
  },
  Zambia: {
    code: 260,
    currency: "K",
  },
};
